#!/bin/sh

rm -f sample.{raw,wav}
python3 demodfm.py $1

# convert txt to wav
make convertasc && ./convertasc demodfm.dat S16LE
sox -r 96000 -L -t s16 -c 1 sample.raw sample.wav gain 0

# play wav file
mplayer sample.wav

# view wav file
#audacity sample.wav

